version: "3.5"

volumes:
  homebridge:

services:
  homebridge:
    build: ./homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Stockholm
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9090
    volumes:
      - homebridge:/homebridge
  rtsp-server:
    image: aler9/rtsp-simple-server:latest
    restart: always
    network_mode: host
  ffmpeg-camera:
    build: ./ffmpeg-camera
    restart: always
    network_mode: host
    environment:
      - RTSP_SERVER_URL=rtsp://rtsp-server:8554/mystream
    devices:
      - /dev/video0:/dev/video
    depends_on:
      - rtsp-server
