version: "3.5"

volumes:
  homebridge:

services:
  homebridge:
    build: ./homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Stockholm
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9090
    volumes:
      - homebridge:/homebridge
